
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('ICBC','中国工商银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('ABC','中国农业银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('CCB','中国建设银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('BOC','中国银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('BCM','中国交通银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('CIB','兴业银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('CITIC','中信银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('CEB','中国光大银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('PAB','平安银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('PSBC','中国邮政储蓄银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('SHB','上海银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('SPDB','浦东发展银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `tbf_channel_bank` (`bank_code`, `bank_name`, `channel_type`, `status`, `channel_bank`, `max_order`, `order_amount`, `day_amount`, `month_amount`, `remark`) values('CIB','兴业银行','40','1',NULL,NULL,NULL,NULL,NULL,NULL);
